# Generated by Django 5.2.6 on 2025-09-19 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweetify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='User',
            new_name='user',
        ),
    ]
